# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/cmsno/Dropbox/Year_5/Project/Vivado_Projects/AES_Key_Expansion/AES_Key_Expansion.cache/wt [current_project]
set_property parent.project_path C:/Users/cmsno/Dropbox/Year_5/Project/Vivado_Projects/AES_Key_Expansion/AES_Key_Expansion.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/cmsno/Dropbox/Year_5/Project/Vivado_Projects/AES_Key_Expansion/AES_Key_Expansion.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/cmsno/Dropbox/Year_5/Project/Vivado_Projects/AES_Key_Expansion/AES_Key_Expansion.srcs/sources_1/new/KeyExpansion.v
  C:/Users/cmsno/Dropbox/Year_5/Project/Vivado_Projects/AES_Key_Expansion/AES_Key_Expansion.srcs/sources_1/new/AES_top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Vivado XDC/digilent-xdc-master/Basys-3-Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Vivado XDC/digilent-xdc-master/Basys-3-Master.xdc}}]


synth_design -top AES_top -part xc7a35tcpg236-1


write_checkpoint -force -noxdef AES_top.dcp

catch { report_utilization -file AES_top_utilization_synth.rpt -pb AES_top_utilization_synth.pb }
